language: cpp
script: cmake

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qttool5-dev
  - sudo apt-get install qt5-default

