site_name: NCL Composer Docs
pages:
- [index.md, 'Iniciando', 'Prefácio']
- [02-introduction.md, 'Iniciando', 'O que é o NCL Composer?']
- [03-getting-started.md, 'Iniciando', 'Instalando o NCL Composer']
- [05-windows-and-menus.md, 'Iniciando', 'Conceitos básicos']
- [05-windows-and-menus.md, 'Iniciando', 'Telas e Menus']
- [06-other-tools.md,'Iniciando', ' Outras ferramentas']
- [tutorial/04.00-tutorial.md, 'Tutoriais', 'Index']
- [tutorial/04.01-tutorial-ex01.md, 'Tutoriais', 'Exemplo 01 - Olá Garrincha!']
- [tutorial/04.02-tutorial-ex02.md, 'Tutoriais', 'Exemplo 02 - Sincronismo sem interatividade']
- [tutorial/04.02-tutorial-ex02.md, 'Avançado', 'Arquitetura do NCL Composer']
- [tutorial/04.02-tutorial-ex02.md, 'Avançado', 'Estendendo o NCL Composer']
- [relnotes/0.1.2.md, 'Release Notes', 'v0.1.2']
- [relnotes/0.1.4.md, 'Release Notes', 'v0.1.4']
- [relnotes/0.1.5.md, 'Release Notes', 'v0.1.5']
- [relnotes/0.1.6.md, 'Release Notes', 'v0.1.6']
- [relnotes/0.1.7.md, 'Release Notes', 'v0.1.7']
- [relnotes/0.1.8.md, 'Release Notes', 'v0.1.8']
- [relnotes/0.1.9.md, 'Release Notes', 'v0.1.9']
- [relnotes/0.2.0.md, 'Release Notes', 'v0.2.0']
- [relnotes/0.2.1.md, 'Release Notes', 'v0.2.1']
- [relnotes/0.3.0.md, 'Release Notes', 'v0.3.0']

docs_dir: pt-br

#theme: cosmo

