site_name: NCL Composer Docs

pages:

- Iniciando:
  - Prefácio: index.md
  - O que é o NCL Composer?: getting-started/02-introduction.md
  - Instalando o NCL Composer: getting-started/03-installing.md
  - Conceitos básicos: getting-started/04-basic-concepts.md
  - Telas e menus: getting-started/05-windows-and-menus.md
  - Outras ferramentas: 06-other-tools.md
- Tutoriais:
  - Olá Garrincha: tutorial/04.01-tutorial-ex01.md
  - Sincronismo sem interatividade: tutorial/04.02-tutorial-ex02.md
- Avançado:
  - Arquitetura do NCL Composer: advanced/01-nclcomposer-architecture.md
  - Estendendo o NCL Composer: advanced/02-extending-nclcomposer.md
- Release notes (English):
  - v0.1.2: 'relnotes/0.1.2.md'
  - v0.1.4: 'relnotes/0.1.4.md'
  - v0.1.5: 'relnotes/0.1.5.md'
  - v0.1.7: 'relnotes/0.1.7.md'
  - v0.1.8: 'relnotes/0.1.8.md'
  - v0.1.9: 'relnotes/0.1.9.md'
  - v0.2.0: 'relnotes/0.2.0.md'
  - v0.2.1: 'relnotes/0.2.1.md'
  - v0.3.0: 'relnotes/0.3.0.md'

docs_dir: pt-br
repo_url: http://github.com/telemidia/nclcomposer
theme: cosmo

