
name: nclcomposer # you probably want to 'snapcraft register <name>'
version: '0.4.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: NCL Composer snap # 79 char long summary
description: |
  TODO.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  nclcomposer:
    command: desktop-launch nclcomposer
    plugs:
      - home

parts:
  nclcomposer:
    plugin: cmake
    build-packages:
      - qtbase5-dev
      - qttools5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5core5a
      - libqt5gui5
      - libqt5xml5
      - libqt5svg5
      - libqt5webkit5
      - libqt5help5
    after: [desktop-qt5] # A wiki part
